# Copyright 2024 sby1ce
# 
# SPDX-License-Identifier: CC0-1.0

[package]
name = "cd-wasm"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
cd-core = { path = "../cd-core" }
js-sys = "0.3"
wasm-bindgen = "0.2"
