# Copyright 2024 sby1ce
#
# SPDX-License-Identifier: CC0-1.0

name: Deploy to GitHub Pages

on:
  push:
    branches: "main"
    paths:
      - ".github/workflows/deploy.yml"
      - "src/**"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      #     cache: npm

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Get cargo-install
        uses: baptiste0928/cargo-install@v3
        with:
          crate: wasm-pack
          version: "^0.12"

      - name: Install dependencies
        run: bun install
        # run: npm install 

      - name: Navigate and check
        run: |
          cd svelte
          bun run check 
      - name: Build Rust
        run: bun run wasm --release

      - name: build
        run: |
          bun --bun run build_
          touch build/.nojekyll
        #   npm run build
        #   touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "svelte/build/"
        # this should match the `pages` option in your adapter-static options

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
